In [1]:
import torch

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [2]:
print(torch.__version__)

2.5.1+cu124


In [5]:
if torch.cuda.is_available():
    print('Gpu available, Gpu name is : ', torch.cuda.get_device_name())
    print('Available gpus : ',torch.cuda.device_count())
else:
    print('Gpu not avaible, CPU is working')
    

Gpu available, Gpu name is :  NVIDIA GeForce GTX 1650
Available gpus :  1


## Creating a tensor

In [7]:
#using empty
empty_tensor = torch.empty(2,4)
empty_tensor

tensor([[-2.3969e-31,  3.2981e-41, -1.1102e-17,  4.4201e-41],
        [ 8.9683e-44,  0.0000e+00,  1.3452e-43,  0.0000e+00]])

In [8]:
type(empty_tensor)

torch.Tensor

In [10]:
# zero tensor of given size
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# tensor of given size with values as 1
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
# tensor with random values (0 to 1) assigned
torch.rand(2,2)

tensor([[0.6765, 0.7539],
        [0.2627, 0.0428]])

In [16]:
#manual seed
torch.manual_seed(100)  #using this rand() method will generate same values everytime
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [22]:
#using tensor to create custom tensors
torch.tensor([[1,2,3],[2,4,6]])

tensor([[1, 2, 3],
        [2, 4, 6]])

In [23]:
#arange
torch.arange(1,10,2) # (start, stop, step)

tensor([1, 3, 5, 7, 9])

In [25]:
#linspace
torch.linspace(1,10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [28]:
#using eye ->identity matrix
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
#using full
torch.full((4,4),5) # -> 4x4 matrix with all values as 5

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

## Tensor shapes

In [31]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [34]:
print(f'shape of x is : {x.shape}')
print(f'shape of x is : {x.size()}')

shape of x is : torch.Size([2, 4])
shape of x is : torch.Size([2, 4])


In [35]:
# create a new tensor of same shape of a given tensor but without the values
torch.empty_like(x)

tensor([[135478893137296, 101088737647120, 101088728987232, 101088733109536],
        [              0, 101088731541376, 101088683975136, 135474581194848]])

In [36]:
# create a new tensor of same shape of a given tensor but with all 0s
torch.zeros_like(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [37]:
torch.ones_like(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [40]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

## Mathematical Operations

In [43]:
print('x is : ',x)
# addition
add = x + 2
print('x + 2 : ',add)

# substraction
minus = x - 2
print('x - 2 : ',minus)

# multiplication
multi = x * 3
print('x * 3 : ',multi)

# division
div = x // 2
print('x // 2 : ',div)

# mod
mod = x % 2
print('x % 2 : ',mod)

# power
power = x ** 2
print('x ** 2 : ',power)

x is :  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
x + 2 :  tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]])
x - 2 :  tensor([[-1,  0,  1,  2],
        [ 3,  4,  5,  6]])
x * 3 :  tensor([[ 3,  6,  9, 12],
        [15, 18, 21, 24]])
x // 2 :  tensor([[0, 1, 1, 2],
        [2, 3, 3, 4]])
x % 2 :  tensor([[1, 0, 1, 0],
        [1, 0, 1, 0]])
x ** 2 :  tensor([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])


## Tensor operations

In [2]:
a= torch.tensor([1,2])
b= torch.tensor([3,4])

# addition
print('a+b : ',a+b)

# substraction
print('a-b : ',a-b)

# muliplication
print('a*b : ',a*b)

# division
print('a//b : ',a//b)

# power
print('a**b : ',a**b)

# mod
print('a%b : ',a%b)


a+b :  tensor([4, 6])
a-b :  tensor([-2, -2])
a*b :  tensor([3, 8])
a//b :  tensor([0, 0])
a**b :  tensor([ 1, 16])
a%b :  tensor([1, 2])


In [3]:
c = torch.tensor([1,-2,3,-4,-5])

torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [5]:
t = torch.tensor([1.3, 5.4, 7.8, 4.7])
print(torch.ceil(t))
print(torch.round(t))
print(torch.floor(t))

tensor([2., 6., 8., 5.])
tensor([1., 5., 8., 5.])
tensor([1., 5., 7., 4.])


## Reduction Operations

In [6]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[5, 8, 8],
        [2, 8, 5]])

In [9]:
#sum
print(torch.sum(e))

#sum along columns
print(torch.sum(e, dim=0))

#sum along rows
print(torch.sum(e, dim=1))

tensor(36)
tensor([ 7, 16, 13])
tensor([21, 15])


In [20]:
#mean
e2 = e.clone()
print(torch.mean(e))

#mean along column
print(torch.mean(e, dim=0))

#mean along row
print(torch.mean(e, dim=1))


tensor(6.)
tensor([3.5000, 8.0000, 6.5000])
tensor([7., 5.])


In [18]:
e2[1][1] = 10
print(e2)

tensor([[ 5.,  8.,  8.],
        [ 2., 10.,  5.]])


In [22]:
#median
torch.median(e2)

#max min
print(torch.max(e2))
print(torch.min(e2))

#std var
print(torch.std(e2))
print(torch.var(e2))

tensor(8.)
tensor(2.)
tensor(2.4495)
tensor(6.)


In [28]:
print('e2 : ',e2)
#argmax
print(torch.argmax(e2)) #position of the largest element in the tensort

#argmin
print(torch.argmin(e2))

e2 :  tensor([[5., 8., 8.],
        [2., 8., 5.]])
tensor(1)
tensor(3)


In [31]:
# matrix multiplication
A = torch.randint(size=(2,3), low=0, high=10)
B = torch.randint(size=(3,2), low=0, high=10)

print('A : ',A)
print('B : ',B)
print('Matrix multiplication : ',torch.matmul(A,B))

A :  tensor([[6, 7, 1],
        [9, 6, 4]])
B :  tensor([[0, 6],
        [0, 1],
        [3, 2]])
Matrix multiplication :  tensor([[ 3, 45],
        [12, 68]])


In [38]:
#dot product
A = torch.randint( low=0, high=10,size=(2,))
B = torch.randint( low=0, high=10,size=(2,))

print('A : ',A)
print('B : ',B)
print('Dot product : ',torch.dot(A,B))

A :  tensor([9, 8])
B :  tensor([0, 7])
Dot product :  tensor(56)


In [48]:
mat = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
torch.transpose(mat, 0,1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [50]:
#determinant
mat2 = mat.clone().to(torch.float32)
torch.det(mat2)

tensor(0.)

In [51]:
import numpy as np
mat3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(mat3)

0.0

## Comparison operators

In [56]:
mat == mat3 # mat is torch tensor and mat3 is numpy array

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [61]:
print(mat > mat2)
print(mat < mat2)
print(mat >= mat2)
print(mat <= mat2)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Special functions

In [62]:
#log function
torch.log(mat,)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])

In [63]:
#square root
torch.sqrt(mat)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])

In [65]:
#sigmoid
torch.sigmoid(mat)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975],
        [0.9991, 0.9997, 0.9999]])

In [68]:
#softmax
torch.softmax(mat2,dim=0) #it requires float values to work

tensor([[0.0024, 0.0024, 0.0024],
        [0.0473, 0.0473, 0.0473],
        [0.9503, 0.9503, 0.9503]])

In [69]:
#relu
torch.relu(mat2)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

## Inplace operations on the tensor directly
This will help us to save the amount of memory by directly adding those new computed values in the place of the tensor. To do this, simply add underscore_ after the fucntion name.  
For Ex: tensor A = [1,2,3,4] and B = [2,3,4,5], inorder to store to value of A + B, we were doing like this torch.add(A,B), insted we will do something like this A.add_(B), this will compute every new value and place it on existing values of A.  
Remember A = A+B will first store the newly calculated values somewhere else not on `A` itself.

In [71]:
print(A,B)

A.add_(B)
print(A,B)

tensor([9, 8]) tensor([0, 7])
tensor([ 9, 15]) tensor([0, 7])


## Copying a tensor

In [73]:
C = A.clone()
D = A

print(id(A), id(C)) # A and C are stored at different locations
print(id(A), id(D)) # A and D are stored at same locations means they are same, if I change value in one, other will also change

135572317401504 135572317399584
135572317401504 135572317401504


## Tensor operations on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')

In [77]:
#creating a new tensor on GPU
torch.ones(2,3, device=device)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [ ]:
#moving a tensor from cpu to gpu
a = torch.ones(2,3)
print(a)
b = a.to(device)
print(b)   

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [2]:
import time
device = torch.device('cuda')
#Define the size of the matrices
size = 10000

mat1 = torch.randn(size, size) #negative numbers
mat2 = torch.rand(size, size) #positive numbers

#measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(mat1, mat2) # matrix multiplication on cpu
cpu_end_time = time.time() - start_time
print(f"Time taken on CPU: {cpu_end_time:4f} seconds")

# move matrices to GPU
mat1 = mat1.to(device)
mat2 = mat2.to(device)

#measure time on GPU
start_time_gpu = time.time()
result_gpu = torch.matmul(mat1, mat2) #matrix multiplication on gpu
gpu_end_time = time.time() - start_time_gpu
print(f"Time taken on GPU: {gpu_end_time:4f} seconds")

print(f'matrix multiplication on gpu is {cpu_end_time//gpu_end_time} times faster')

## Reshaping tensors

Time taken on CPU: 11.163714 seconds
Time taken on GPU: 0.095233 seconds
matrix multiplication on gpu is 117.0 times faster


In [7]:
A = torch.ones(4,4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
#reshape
A.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [9]:
#flatten
A.flatten() # converts into vector

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#permute
B = torch.rand(2,3,4)
print(B.shape)
print(B.permute(2,0,1).shape)

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [16]:
#unsqueeze

c= torch.rand(226,226,3)

print(c.shape)
print(c.unsqueeze(2).shape)  #adds a new dimension at defined locaiton

print(c.unsqueeze(1).shape) #adds a new dimension at defined locaiton

torch.Size([226, 226, 3])
torch.Size([226, 226, 1, 3])
torch.Size([226, 1, 226, 3])


In [18]:
#squeeze
d = torch.rand(266,266,3)
print(d.squeeze(1).shape)  #removes dimension at defined location

torch.Size([266, 266, 3])


## Numpy and PyTorch

In [19]:
import numpy as np

In [20]:
#from numpy to tensor
arr1 = np.array([1,2,3,4,5])
arr2 = torch.from_numpy(arr1)
print(arr1, arr2)

[1 2 3 4 5] tensor([1, 2, 3, 4, 5])


In [21]:
#from tensor to numpy
arr3 = arr2.numpy()
arr3

array([1, 2, 3, 4, 5])