In [1]:
from sklearn.datasets import make_classification
import torch

In [7]:
X, y = make_classification(
    n_samples=20,
    n_features=2,
    n_informative=2,
    n_classes=2,
    n_redundant=0,
    random_state=42
)

In [8]:
X

array([[-0.28280607, -1.40876083],
       [ 0.94702918,  0.55906844],
       [ 1.15772163,  0.474995  ],
       [ 1.99591479,  0.77282149],
       [ 0.04049985,  1.39732687],
       [ 1.47044441, -0.86055081],
       [-0.70743459,  0.89217168],
       [-1.45694256, -0.04564786],
       [ 0.62203454,  2.36749526],
       [-0.01544395,  1.09258513],
       [ 1.61125245, -0.65678116],
       [ 1.45454184,  0.91354664],
       [-0.20714752,  1.33055499],
       [ 1.9632335 , -0.7697201 ],
       [-0.96400678, -0.82990054],
       [ 2.07569216,  0.66009587],
       [-0.65503537, -0.83585632],
       [-1.42571554, -1.31373391],
       [-0.87496777, -0.11350669],
       [ 1.25579369, -0.37205015]])

In [4]:
y

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [5]:
# converting numpy arrays to Pytorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32)

In [6]:
X_tensor

tensor([[-0.2828, -1.4088],
        [ 0.9470,  0.5591],
        [ 1.1577,  0.4750],
        [ 1.9959,  0.7728],
        [ 0.0405,  1.3973],
        [ 1.4704, -0.8606],
        [-0.7074,  0.8922],
        [-1.4569, -0.0456],
        [ 0.6220,  2.3675],
        [-0.0154,  1.0926],
        [ 1.6113, -0.6568],
        [ 1.4545,  0.9135],
        [-0.2071,  1.3306],
        [ 1.9632, -0.7697],
        [-0.9640, -0.8299],
        [ 2.0757,  0.6601],
        [-0.6550, -0.8359],
        [-1.4257, -1.3137],
        [-0.8750, -0.1135],
        [ 1.2558, -0.3721]])

In [9]:
from torch.utils.data import Dataset, DataLoader

In [10]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]
    

In [11]:
dataset = CustomDataset(X_tensor, y_tensor)

In [12]:
dataset.__len__()

20

In [14]:
dataset.__getitem__(2)

(tensor([1.1577, 0.4750]), tensor(0.))

In [25]:
data_loader = DataLoader(dataset, batch_size=4, shuffle=True)

In [27]:
for batch_features, batch_labels in data_loader:
    print("Inputs : ",batch_features)
    print("Outputs : ",batch_labels)
    print('-'*50)

Inputs :  tensor([[ 1.1577,  0.4750],
        [-0.9640, -0.8299],
        [-0.2071,  1.3306],
        [ 1.9959,  0.7728]])
Outputs :  tensor([0., 0., 1., 1.])
--------------------------------------------------
Inputs :  tensor([[ 1.4704, -0.8606],
        [-0.0154,  1.0926],
        [ 0.9470,  0.5591],
        [-1.4569, -0.0456]])
Outputs :  tensor([0., 1., 0., 1.])
--------------------------------------------------
Inputs :  tensor([[ 2.0757,  0.6601],
        [-0.8750, -0.1135],
        [ 0.6220,  2.3675],
        [ 1.4545,  0.9135]])
Outputs :  tensor([1., 1., 0., 1.])
--------------------------------------------------
Inputs :  tensor([[-0.7074,  0.8922],
        [ 1.6113, -0.6568],
        [ 1.9632, -0.7697],
        [ 1.2558, -0.3721]])
Outputs :  tensor([1., 0., 0., 0.])
--------------------------------------------------
Inputs :  tensor([[-0.6550, -0.8359],
        [ 0.0405,  1.3973],
        [-1.4257, -1.3137],
        [-0.2828, -1.4088]])
Outputs :  tensor([0., 1., 0., 0.])
-